### ISSUE TITLE
release 1.2.1

### ISSUE THREAD

**Issue by vrozov** [DataTorrent/Netlet#45]

**Comment by vrozov** [comment]
@243826 Will it be OK releasing 1.2.1 with #42, #43 and #44?

**Comment by 243826** [comment]
44 is good to go. I think the changes in #42 and #43 are okay design wise. logging aspect is unfriendly to applications. I do not want to see the my logs cluttered with lower level logging if I am dealing with the exceptions myself (raising exceptions by library is a right thing to do).

**Comment by vrozov** [comment]
Released netlet 1.2.1 to maven central repository.
