### ISSUE TITLE
I plan to change master branch to track release-1.3.0.

### ISSUE THREAD

**Issue by vrozov** [DataTorrent/Netlet#50]
I need to make patch incompatible API changes. Please let me know if there are any objections.  Otherwise, I will proceed with the push.

**Comment by 243826** [comment]
what this change is?

**Comment by vrozov** [comment]
At a minimum, I'd like to introduce more constructors to AbstractLengthPrependerClient() and be able to increase `AbstractClient.writeBuffer` lenght for Server.Subscriber.

**Comment by 243826** [comment]
Sure. do not foresee any harm.?


--

Chetan


________________________________

**Comment by PramodSSImmaneni** [comment]
Sounds good to me..

**Comment by vrozov** [comment]
OK, thanks. Proceeding with the forced push. The current branch is preserved as release-1.2.
